name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout the repository
      uses: actions/checkout@v4
      
    - name: Use Node.js v20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: "npm"
        
    - name: Install the dependencies 
      run: npm install
      
    - name: Start the app
      run: npm start &

    - name: Run the Unit tests
      run: npm run test:unit
      
    - name: Display SoftUni username
      run: echo "deyan2306"
  
  ui_tests:

    needs: build_and_test
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Use Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install the dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Start the app
        run: npm start &

      - name: Run the UI tests
        run: npm run test:ui

  deploy_to_render:
    needs: ui_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

