name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      
    - name: Use Node.js v20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies 
      run: npm install
    
    - name: Install playwright browsers
      run: npx playwright install
      
    - name: Start the app
      run: npm start &

    - name: Run UI tests
      run: npm run test:ui
      
    - name: Display SoftUni username
      run: echo "deyan2306"

  deploy_on_render:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Auto deploy to render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with: 
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

